"""
Signal Model - Trading signals generated by the system
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Type of trading signal"""
    WHALE_BUY = "whale_buy"
    WHALE_SELL = "whale_sell"
    SMART_MONEY_ENTRY = "smart_money_entry"
    SMART_MONEY_EXIT = "smart_money_exit"
    SENTIMENT_SPIKE = "sentiment_spike"
    SENTIMENT_DROP = "sentiment_drop"
    VOLUME_SURGE = "volume_surge"
    LIQUIDITY_CHANGE = "liquidity_change"
    NEW_LISTING = "new_listing"
    INFLUENCER_MENTION = "influencer_mention"
    RUG_RISK = "rug_risk"
    PUMP_DETECTED = "pump_detected"
    DUMP_DETECTED = "dump_detected"
    DEV_ACTIVITY = "dev_activity"
    LP_UNLOCK = "lp_unlock"
    CONTRACT_RISK = "contract_risk"
    PRICE_BREAKOUT = "price_breakout"
    HOLDER_SURGE = "holder_surge"


class SignalStrength(str, Enum):
    """Signal strength/confidence level"""
    WEAK = "weak"           # < 30% confidence
    MODERATE = "moderate"   # 30-60% confidence
    STRONG = "strong"       # 60-85% confidence
    VERY_STRONG = "very_strong"  # > 85% confidence


class Signal(BaseModel):
    """Trading signal generated by analysis"""
    signal_id: str = Field(default_factory=lambda: f"sig_{uuid.uuid4().hex[:12]}")
    token_id: str = ""
    token_symbol: str = ""
    token_address: str = ""
    chain: str = "solana"
    
    # Signal Details
    signal_type: SignalType = SignalType.VOLUME_SURGE
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = 0.0  # 0.0 to 1.0
    
    # Description
    title: str = ""
    description: str = ""
    action_suggestion: str = ""  # Human-readable suggestion
    
    # Supporting Data
    data_points: Dict[str, Any] = Field(default_factory=dict)
    source: str = ""  # e.g., "on_chain_monitor", "sentiment_agent", "whale_tracker"
    related_wallets: List[str] = Field(default_factory=list)
    related_txs: List[str] = Field(default_factory=list)
    
    # Price Context
    price_at_signal: float = 0.0
    price_target: Optional[float] = None
    stop_loss: Optional[float] = None
    
    # Timing
    is_active: bool = True
    expires_at: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Signal":
        return cls(**data)
